const images = {
   App_logo: require('./Applogo.png'),
   Color_picker_image: require('./colorpicker.png'),
   First_Swiper: require('./LottieAnimation/FirstSwiper.json'),
   Two_Swiper: require('./LottieAnimation/TwoSwiper.json'),
   Three_Swiper: require('./LottieAnimation/ThreeSwiper.json'),
   Splash_Swiper: require('./LottieAnimation/SplashScreen.json'),
   Account_created: require('./LottieAnimation/Accountcreated.json'),
   Google_image: require('./googleicon.png'),
   UxDisigner_Digner: require('./LottieAnimation/UxDisigner.json'),
   Facebook_animation: require('./LottieAnimation/Facebook.json'),
   Left_aerrow_details: require('./LottieAnimation/Leftaerrows.json'),
   Likeanimation: require('./LottieAnimation/LikeImages.json'),
   Codingimage_one: require('./codingfive.png'),
   Codingimage_two: require('./codingthree.png'),
   Codingimage_three: require('./codingtwo.png'),
   UXdEsigner_one: require('./Uxsigner.png'),
   UXdEsigner_two: require('./Uxdesignertwo.png'),
   UXdEsigner_three: require('./Uxdesignerthree.png'),
   UxDisignerfourt_file: require('./UxDisignerfourt.png'),
   User_image_one_profile: require('./userdp.jpg'),
   Chat_image_one: require('./userfiveimag.png'),
   Chat_image_two: require('./userfourimage.png'),
   Chat_image_three: require('./userimagesaven.png'),
   Chat_image_four: require('./userimagetwo.png'),
   Chat_image_five: require('./userimagthree.png'),
   Chat_image_six: require('./userone.png'),
   Chat_image_saven: require('./usersiximage.png'),
   Chat_image_aeight: require('./userfiveimag.png'),
   Languageanimation: require('./LottieAnimation/languageanimation.json'),
}
export default images;