export const COMMON_LOADING = 'COMMON_LOADING';
export const COLOR_PICKER_SET = "COLOR_PICKER_SET";
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const ADD_PRODUCT_DATA = 'ADD_PRODUCT_DATA';
export const CREATE_SELL_INVOICE_DATA = 'CREATE_SELL_INVOICE_DATA';
export const GET_ALL_PINO_LIST = 'GET_ALL_PINO_LIST';
export const GET_SETTING_API_DATA = 'GET_SETTING_API_DATA';
export const CREATE_PAYMENT_DATA = 'CREATE_PAYMENT_DATA';
export const CREATE_PURCHASE_DATA = 'CREATE_PURCHASE_DATA';
export const CREATE_EXPENSE_DATA = 'CREATE_EXPENSE_DATA';
export const CREATE_EXPORT_DATA = 'CREATE_EXPORT_DATA';
export const GATE_SELL_INVOICE_DATA = 'GATE_SELL_INVOICE_DATA';
export const DELETE_SELL_INVOICE_DATA = 'DELETE_SELL_INVOICE_DATA';
export const GET_PAYMENT_DATA = 'GET_PAYMENT_DATA';
export const DELETE_PAYMENT_DATA = 'DELETE_PAYMENT_DATA';

export const GET_PURCHASE_DATA = 'GET_PURCHASE_DATA';
export const DELETE_PURCHASE_DATA = 'DELETE_PURCHASE_DATA';

export const GET_EXPENSE_DATA = 'GET_EXPENSE_DATA';
export const DELETE_EXPENSE_DATA = 'DELETE_EXPENSE_DATA';

export const GET_EXPORT_DATA = 'GET_EXPORT_DATA';
export const DELETE_EXPORT_DATA = 'DELETE_EXPORT_DATA';

export const ERROR_HANDLING_DATA = 'ERROR_HANDLING_DATA';

export const GET_USER_PERMISSION_DATA = 'GET_USER_PERMISSION_DATA';
